#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -euo pipefail

echo "-------------------------------------"
echo "LSIO-style image"
echo "Image: ${APP_NAME:-unknown} ${APP_VERSION:-unknown}"
echo "-------------------------------------"

